name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  haystack: # change this
    required: true
    description: 'The string in which to search for matches'
  needle:
    required: false
    default: '/[A-Z]+-\d+/gmi'
    description: 'The regex that is used to find matches in `heaystack`'
runs:
  using: 'node16'
  main: 'dist/index.js'
