name: "Example Workflow"

on:
  issues:
    types: [ labeled ]

jobs:
  inspect-issue-body:
    runs-on: ubuntu-latest
    steps:
      - name: Using defaults
        uses: paulschuberth/regex-extract-action@v0.1.0
        id: example-default
        with:
          haystack: ${{ github.event.issue.body }}
       
      - name: Use output of default settings
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.example-default.outputs.matches }}
            })
